---
- name: "enable {{ service_name }} on windows server"
  win_service:
    name: "{{ service_name }}"
    state: started
  when: ansible_distribution == "Microsoft Windows Server 2012 R2 Standard"
  