---
- name: configure yum repositories on all servers
  hosts: all
  gather_facts: false # remove later! speeds up testing
  become: true
  roles:
    - rhel7

- name: deploy haproxy
  hosts: frontends
  gather_facts: false
  become: true
  roles:
    - haproxy
  vars:
    - GUID: b5f1

- name: deploy tomcat
  hosts: apps
  gather_facts: false
  become: true
  vars_files:
    - vars/main.yml
  roles:
    - tomcat

- name: deploy postgres
  hosts: appdbs
  gather_facts: false
  become: true
  vars_files:
    - vars/main.yml
  roles:
    - postgresql

- name: deploy apache
  hosts: apps
  gather_facts: false
  become: true
  vars_files:
    - vars/main.yml
  roles:
    - apache