---
- name: install packages from a list
  win_chocolatey:
    name: "{{ item }}"
    state: latest
    params: "{{ parameters }}"
  when: ansible_distribution == "Microsoft Windows Server 2012 R2 Standard"
  with_items:
    - "{{ package_name }}"
